export const UI_OPEN_SIDEBAR = 'UI_OPEN_SIDEBAR'
export const UI_CLOSE_SIDEBAR = 'UI_CLOSE_SIDEBAR'
export const UI_ADD_ENTRY = 'UI_ADD_ENTRY'
export const ENTRY_LIST = 'ENTRY_LIST'
export const ENTRY_ADD = 'ENTRY_ADD'
export const ENTRY_UPDATE = 'ENTRY_UPDATE'
export const ENTRY_DELETE = 'ENTRY_DELETE'